version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "darkshore"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2wk4oybze5xe"
s3_prefix = "darkshore"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
